#!/usr/bin/env zsh
#
# Utilize GNU Stow to update existing and push new dotfiles

# Track all modules with GNU Stow 
for MODULE in $(just find_modules); do 
    stow . --dir="./config/${MODULE}" --target ~/
    if [[ $? -eq 0 ]]; then
        echo "Succesfully Stowed ${MODULE}"
    fi
done

