#!/usr/bin/env zsh
#
# Utilize GNU Stow to update existing and push new dotfiles

# Track all home modules with GNU Stow
for MODULE in $(just find_modules_home); do
    stow --restow . --dir="./config/home/${MODULE}/" --target="$HOME/"
    if [[ $? -eq 0 ]]; then
        echo "Succesfully Stowed ${MODULE}, path: ${HOME}/${MODULE}"
    fi
done

# Track all modules with GNU Stow
for MODULE in $(just find_modules_etc); do
    sudo stow --restow . --dir="./config/etc/${MODULE}/" --target="/etc/"
    if [[ $? -eq 0 ]]; then
        echo "Succesfully Stowed ${MODULE}, path: /etc/${MODULE}"
    fi
done

